
# "service" is the name of this project. This will also be added to your AWS resource names.
service: ContentCreation

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${env:OPENAI_API_KEY}
    BUCKET_NAME : ${env:BUCKET_NAME}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - sqs:ReceiveMessage
            - sqs:DeleteMessage
            - sqs:GetQueueAttributes
            - sqs:SendMessage
          Resource:
            - Fn::GetAtt:
                - ContentCreatorQueue
                - Arn
            - Fn::GetAtt:
                - ContentCreatorDLQ
                - Arn

        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:BUCKET_NAME}/*
            - arn:aws:s3:::${env:BUCKET_NAME}

functions:
  generate:
    handler: handler.generate
    reservedConcurrency: 10
    provisionedConcurrency: 3
    timeout: 900
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - ContentCreatorQueue
              - Arn
          batchSize: 10
          enabled: true
          
    layers:
      - arn:aws:lambda:us-east-1:512195023911:layer:content-layer:2


resources:
  Resources:
    ContentCreatorQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ContentCreatorQueue"
        VisibilityTimeout: 900
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - ContentCreatorDLQ
              - Arn
          maxReceiveCount: 2

    ContentCreatorDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "ContentCreatorDLQ"
